---
env:
  - DISTRO=debian
  - DISTRO=rhel
sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install -r requirements.txt
script: "molecule test -s $DISTRO"
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
