---
# tasks file for ansible-role-hass
- name: Import Variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/{{ ansible_os_family }}.yml"
    - vars/default.yml

- name: Include OS dependencies
  include_tasks: "tasks/{{ ansible_os_family }}-deps.yml"

- name: Include Common dependencies
  include_tasks: tasks/common-deps.yml