---
# handlers file for ansible-role-hass
- name: home-assistant enable
  systemd:
    name: "home-assistant@{{ hass_user }}.service"
    enabled: "yes"
    state: started
    daemon_reload: "yes"

- name: appdaemon enable
  systemd:
    name: "appdaemon@{{ hass_user }}.service"
    enabled: "yes"
    state: started
    daemon_reload: "yes"
