---
dependency:
  name: galaxy
  # options:
  #   role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos7
    image: centos:7
    command: "/lib/systemd/systemd"
    privileged: true
  - name: stretch
    image: geerlingguy/docker-debian9-ansible:latest
    command: "/lib/systemd/systemd"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
  - name: ubuntu18
    image: geerlingguy/docker-ubuntu1804-ansible:latest
    command: "/lib/systemd/systemd"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        hass_install_appdaemon: true
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
